name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install binutils-arm-none-eabi gcc-arm-none-eabi
        rustup target add thumbv8m.main-none-eabihf
    - name: Build
      run: |
        cargo build --verbose
        arm-none-eabi-size target/thumbv8m.main-none-eabihf/debug/rust-baremetal-debug
